<?php
/** GENERATED FILE. Source: wordpress-theme/route-manifest.mjs. */
return array(
    array(
        'path' => '/',
        'slug' => 'home',
        'title' => 'Главная',
        'parent_path' => null,
        'output' => 'front-page.php',
        'menu_order' => 0,
        'menu_label' => 'Главная',
    ),
    array(
        'path' => '/uslugi/',
        'slug' => 'uslugi',
        'title' => 'Услуги',
        'parent_path' => null,
        'output' => 'page-uslugi.php',
        'menu_order' => 10,
        'menu_label' => 'Услуги',
    ),
    array(
        'path' => '/uslugi/audit-sistemy-prodazh-otelya/',
        'slug' => 'audit-sistemy-prodazh-otelya',
        'title' => 'Аудит системы продаж отеля',
        'parent_path' => '/uslugi/',
        'output' => 'page-audit-sistemy-prodazh-otelya.php',
        'menu_order' => null,
        'menu_label' => null,
    ),
    array(
        'path' => '/o-proekte/',
        'slug' => 'o-proekte',
        'title' => 'О проекте',
        'parent_path' => null,
        'output' => 'page-o-proekte.php',
        'menu_order' => 20,
        'menu_label' => 'О проекте',
    ),
    array(
        'path' => '/kejsy/',
        'slug' => 'kejsy',
        'title' => 'Кейсы',
        'parent_path' => null,
        'output' => 'page-kejsy.php',
        'menu_order' => 30,
        'menu_label' => 'Кейсы',
    ),
    array(
        'path' => '/poleznoe/',
        'slug' => 'poleznoe',
        'title' => 'Полезное',
        'parent_path' => null,
        'output' => 'page-poleznoe.php',
        'menu_order' => 40,
        'menu_label' => 'Полезное',
    ),
    array(
        'path' => '/poleznoe/stati/kak-provesti-audit-prodazh-otelya/',
        'slug' => 'kak-provesti-audit-prodazh-otelya',
        'title' => 'Как провести аудит продаж отеля',
        'parent_path' => '/poleznoe/stati/',
        'output' => 'page-kak-provesti-audit-prodazh-otelya.php',
        'menu_order' => null,
        'menu_label' => null,
    ),
    array(
        'path' => '/poleznoe/meropriyatiya/industriya-gostepriimstva-2026/',
        'slug' => 'industriya-gostepriimstva-2026',
        'title' => 'Индустрия гостеприимства',
        'parent_path' => '/poleznoe/meropriyatiya/',
        'output' => 'page-industriya-gostepriimstva-2026.php',
        'menu_order' => null,
        'menu_label' => null,
    ),
    array(
        'path' => '/poleznoe/materialy/chek-list-audita-prodazh/',
        'slug' => 'chek-list-audita-prodazh',
        'title' => 'Чек-лист аудита продаж отеля',
        'parent_path' => '/poleznoe/materialy/',
        'output' => 'page-chek-list-audita-prodazh.php',
        'menu_order' => null,
        'menu_label' => null,
    ),
    array(
        'path' => '/kontakty/',
        'slug' => 'kontakty',
        'title' => 'Контакты',
        'parent_path' => null,
        'output' => 'page-kontakty.php',
        'menu_order' => 50,
        'menu_label' => 'Контакты',
    ),
    array(
        'path' => '/politika-konfidencialnosti/',
        'slug' => 'politika-konfidencialnosti',
        'title' => 'Политика конфиденциальности',
        'parent_path' => null,
        'output' => 'page-politika-konfidencialnosti.php',
        'menu_order' => null,
        'menu_label' => null,
    ),
    array(
        'path' => '/soglasie-na-obrabotku-personalnyh-dannyh/',
        'slug' => 'soglasie-na-obrabotku-personalnyh-dannyh',
        'title' => 'Согласие на обработку персональных данных',
        'parent_path' => null,
        'output' => 'page-soglasie-na-obrabotku-personalnyh-dannyh.php',
        'menu_order' => null,
        'menu_label' => null,
    ),
    array(
        'path' => '/politika-cookie/',
        'slug' => 'politika-cookie',
        'title' => 'Политика использования Cookie',
        'parent_path' => null,
        'output' => 'page-politika-cookie.php',
        'menu_order' => null,
        'menu_label' => null,
    ),
    array(
        'path' => '/poleznoe/stati/',
        'slug' => 'stati',
        'title' => 'Статьи',
        'parent_path' => '/poleznoe/',
        'output' => 'page-stati.php',
        'menu_order' => null,
        'menu_label' => null,
    ),
    array(
        'path' => '/poleznoe/meropriyatiya/',
        'slug' => 'meropriyatiya',
        'title' => 'Мероприятия',
        'parent_path' => '/poleznoe/',
        'output' => 'page-meropriyatiya.php',
        'menu_order' => null,
        'menu_label' => null,
    ),
    array(
        'path' => '/poleznoe/materialy/',
        'slug' => 'materialy',
        'title' => 'Материалы',
        'parent_path' => '/poleznoe/',
        'output' => 'page-materialy.php',
        'menu_order' => null,
        'menu_label' => null,
    ),
);
